version: '3.8'

services:
  db:
#    image: postgres:alpine
    image: postgres:15.3
    ports:
# host to local machine
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog